name: CI React

on:
  push:
    branches: [workflow]
  # pull_request:
  #   branches: [develop]

jobs:
  app_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run format:check
      - run: npm test -- --coverage
        env: 
          CI: true