name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app: 
        image: node:16
      mongo:
        image: mongo
        ports:
          - "27017:27017"  

    steps:
      - name: Log node node-version
        run: | 
          node -v
          cat /etc/os-release

      - name: Test Mongo Connection
        run: curl http://localhost:27017
