name: Matrix
on: push

jobs:
  node-version:
    runs-on:  ubuntu-latest
    steps:
      - name: Log node node-version 
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: 6
      - name: Log new node node-version 
        run: node -v
        
