name: Matrix
on: push

jobs:
  node-version:
    runs-on:  ubuntu-latest
    steps:
      - name: Log node node-version 
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: 6
      - name: Log new node node-version 
        run: node -v
        
  node-matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        exclude:
          - os: macos-latest
            node_version: 10
      fail-fast: true
      max-parallel: 3
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Log node node-version 
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log new node node-version 
        run: node -v
        
  
